spring:
  application:
    name: hmily-dubbo-tcc-trade

  main:
    allow-bean-definition-overriding: true
    web-application-type: none

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmily-dubbo?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

dubbo:
  scan:
    base-packages: com.geek.hmilydubbotcc.trade.service
  registry:
    address: N/A
#    address: zookeeper://localhost:2181
#  metadata-report:
#    address: zookeeper://localhost:2181